language: python

python:
  - '3.5'

include:
  - name: "3.5 Unit Test"
    python: "3.5"
    env: TEST_SUITE=suite_3_5_unit

# Install the codecov pip dependency
install:
  - pip install codecov

#command to run tests
script:
  - coverage run test_compute_easter_date.py

after_success:
  - codecov
